### PR TITLE
Add global_timer option

### PR DESCRIPTION
**Pull request by Xrayya**
Most of the time, I just want discord presence to show how long I've been using neovim in total, not how long I've been in a buffer or doing something. When I was actively editing and switching files, the timer rarely touched 10 seconds. This PR addresses that.

### CODE REVIEW

**Comment by Xrayya** [comment]
Wait, I actually find weird behavior while testing this, several hours ago, this works as I expected, but doesn't work at all right now. I'm gonna close this first, may be if I can figure it out, I'll open this later

**Comment by Xrayya** [comment]
Nevermind, my fault, typo on calling setup

**Comment by IogaMaster** [comment]
Thank you!

**Comment by NextPr0gram** [comment]
> Nevermind, my fault, typo on calling setup

how did you fix it?

**Pull request merged**
